config:
    clientID: bcbf1f41-02d4-4b1d-b3b9-f4a0fb8c0f9b
    clientSecret: Fb38Q~sas.9rymYE-W6kxmGjyU0h8.pkVhACtck9
    cookieSecret: R5bY5cYfsrQzJW9-DJ9Y2FNgo4cnbwtR5as435PpJbs=
    configFile: |-
        email_domains = "*"
        upstreams = [ "http://canary-demo.agic.svc.cluster.local:80" ]
        cookie_secure = "false"
        cookie_domains= [ "" ]
        whitelist_domains = [ "agic-prod.com" ]
        reverse_proxy = "true"
        silence_ping_logging = "true"
        # Auth0 provider
        redirect_url = "http://agic-prod.com/oauth2/callback"
        oidc_issuer_url = "https://login.microsoftonline.com/86c45987-0984-4122-a84c-d713fcba108b/v2.0"
        provider = "oidc"
        provider_display_name = "Azure AD"
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        cert-manager.io/cluster-issuer: letsencrypt-kubecost
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - agic-prod.com
    tls:
    - hosts:
      - agic-prod.com
      secretName: kubecost-cert