apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://medium.oauth2.nginx/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://medium.oauth2.nginx/oauth2/start?rd=https://medium.oauth2.nginx/oauth2/callback"
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
spec:
  ingressClassName: nginx
   #tls:
   #- hosts:
   # - kubecost-kris.unicorndomain.com
   # secretName: kubecost-cost-analyzer-tls-cert
  rules:
  - host: medium.oauth2.nginx
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: canary-demo
            port:
              number: 80
